version: 2.1

orbs:
  packtracker: packtracker/report@2.2.6

jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: Check versions
          command: |
            node --version
            yarn --version

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn run build

      - run:
          name: Verify storybook setup
          command: yarn run build:storybook

workflows:
  version: 2
  build:
    jobs:
      - build

  packtracker:
    jobs:
      - packtracker/report
